package com.yayo.warriors.socket.handler.user;


public interface UserCmd {
	int HEART_BEAT = 0;
	int ACCOUNT_LOGIN = 1;
	int CREATE_CHARACTER = 2;
	int LIST_BRANCHINGES = 3;
	int SELECT_CHARACTER = 4;
	int GET_PLAYER_ATTRIBUTE = 5;
	int BINDING_NEW_SESSION = 6;
	int CHANGE_CHANGE_MODE = 7;
	int BACK_REVIVE = 8;
	int PROPS_REVIVE = 9;
	int GUIDE_SAVE = 10;
	int RECEIVE_GUIDE_REWARDS = 11;
	int LIST_CAMP_PLAYERCOUNT = 12;
	int SAVE_ADULT_MESSAGE = 13;
	int SETTING_FASHIONSHOW = 14;
	int GET_PLAYER_ONLINETIME = 15;
	int UPDATE_PLAYER_CAPACITY = 16;
	int CAMP_BATTLE_REVIVE = 17;
	int REQ_OFFLINE = 18;
	int NOTICE_2_KICK = 100;
	int PUSH_ATTRIBUTE_2_MEMBERS = 102;
	int PUSH_PLAYER_LEVELUP = 103;
	int PUSH_MODE_WITH_CHGMAP = 104;
	int PUSH_ROLE_RESURRECT = 105;
	int PUSH_PLAYER_ATTRCHANGE = 106;
}
