package com.yayo.warriors.module.task.type;

public interface EventType {
	int TALK = 1;
	int MESSENGE = 2;
	int KILLS = 3;
	int KILL_COLLECT = 4;
	int PLAYER_LEVEL = 5;
	int PET_LEVEL = 6;
	int ASCENT_EQUIP_STAR = 7;
	int INSTANCE = 8;
	int POLISH_EQUIP_COUNT = 9;
    int COLLECT = 10;
	int BUY_EQUIP_COUNT = 11;
	int BUY_PROPS_COUNT = 12;
	int ENTER_CAMP_TASK = 13;
	int PET_GROW_LEVEL_TASK = 14;
	int PET_SAVVY_LEVEL_TASK = 15;
	int HORSE_LEVEL_TASK = 16;
	int BUY_MALL_ITEM_TASK = 17;
	int ADD_FRIEND_TASK = 18;
	int HORSE_SENIOR_FANCY_TASK = 19;
	int LETTORY_TASK = 20;
	int ENCHANGE_EQUIP_TASK = 21;
	int JOIN_ALLIANCE_TASK = 22;
	int RUSH_MERIDIAN_TASK = 23;
	int MORTAL_LEVELUP_TASK = 24;
	int KILL_CAMP_PLAYER = 25;
	int ESCORT_TASK = 26;
	int DONATE_ALLIANCE_TASK = 27;
	int PLUNDER_ESCORT_TASK = 28;
	int TREASURE_ALLIANCE_TASK = 29;
	int KILL_CAMP_PLAYER_ALLIANCE_TASK = 30;
	int KILL_MONSTER_ALLIANCE_TASK = 31;
}

